spring:
  main:
    allow-bean-definition-overriding: true
  config:
    import:
      - "env/mysql.yml"
      - "env/port.yml"
      - "env/image.yml"
      - "env/redis.yml"
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${mysql_endpoint}
    username: ${mysql_username}
    password: ${mysql_password}
  data:
    redis:
      host: ${redis_host}
      port: ${redis_port}
      password: ${redis_password}
  session:
    store-type: redis
    redis:
      namespace: spring:session
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: update
      use_sql_comments: true
      format_sql: true


server:
  port: ${server_port}
