name: Java CI with Gradle

on:
  push:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4
      - name: JDK 17세팅
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: properties 설정
        run: |
          mkdir -p ./src/main/resources/env
          touch ./src/main/resources/env/mysql.yml
          touch ./src/main/resources/env/port.yml
          printf "%s" "${{ secrets.MYSQL}}" > ./src/main/resources/env/mysql.yml
          printf "%s" "${{ secrets.SERVICE_PORT}}" > ./src/main/resources/env/port.yml

      - name: gradlew 권한 설정
        run: |
          chmod +x ./gradlew

      - name: 빌드
        run: |
          ./gradlew clean build -x test

      - name: JAR 파일 복사
        uses: actions/upload-artifact@v2
        with:
          name: focus-jar
          path: |
            build/libs/*.jar

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: JAR 파일 다운로드
        uses: actions/download-artifact@v2
        with:
          name: focus-jar

      - name: 원격 서버로 JAR 파일 전송
        uses: appleboy/scp-action@v0.1.7
        with:
          debug: true
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER_NAME }}
          password: ${{ secrets.PASS_WORD }}
          port: ${{ secrets.PORT }}
          timeout: 70s
          proxy_timeout: 70s
          command_timeout: 120s
          source: "*.jar"
          target: ${{ secrets.REMOTE_DIRECTORY }}

      - name: 원격 서버에서 애플리케이션 실행
        uses: appleboy/ssh-action@v1.0.3
        with:
          debug: true
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER_NAME }}
          password: ${{ secrets.PASS_WORD }}
          port: ${{ secrets.PORT }}
          timeout: 70s
          proxy_timeout: 70s
          command_timeout: 120s
          script: |
            chmod +x ${{ secrets.REMOTE_DIRECTORY }}/deploy.sh
            sh ${{ secrets.REMOTE_DIRECTORY }}/deploy.sh
