name: Java CI with Gradle

on:
  push:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4
      - name: JDK 17세팅
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: properties 설정
        run: |
          mkdir -p ./src/main/resources/env
          touch ./src/main/resources/env/mysql.yml
          printf "%s" "${{ secrets.MYSQL}}" > ./src/main/resources/env/mysql.yml

      - name: gradlew 권한 설정
        run: |
          chmod +x ./gradlew

      - name: 빌드
        run: |
          ./gradlew clean build -x test

      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@v1.0.3
        with:
          # SSH config
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER_NAME }}
          password: ${{ secrets.PASS_WORD }}
          port: ${{ secrets.PORT }}
          timeout: 70s
          proxy_timeout: 70s
          script: whoamis